.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JUMP" "1" "January 2018" "" ""
.
.SH "NAME"
\fBjump\fR \- navigate faster by learning your habits
.
.SH "SYNOPSIS"
\fBj\fR [term \.\.\.]
.
.SH "DESCRIPTION"
\fBJump\fR integrates with the shell and learns about your navigational habits by keeping track of the directories you visit\. It strives to give you the best directory for the shortest search term\.
.
.SH "USAGE"
Jump needs to be integrated with the shell\. For \fBbash\fR and \fBzsh\fR, the the line below in needs to be in \fB~/\.bashrc\fR, \fB~/bash_profile\fR or \fB~/\.zshrc\fR:
.
.IP "" 4
.
.nf

eval "$(jump shell)"
.
.fi
.
.IP "" 0
.
.P
For fish shell, put the line below needs to be in \fB~/\.config/fish/config\.fish\fR:
.
.IP "" 4
.
.nf

status \-\-is\-interactive; and \. (jump shell | psub)
.
.fi
.
.IP "" 0
.
.P
Once integrated, \fBjump\fR will automatically directory changes and start building an internal database\.
.
.SS "HELPER"
Once integrated, \fBjump\fR introduces the \fBj\fR helper\. It accepts only search terms and as a design goal there are no arguments to \fBj\fR\. Whatever you give it, it\'s treated as search term\.
.
.P
\fBJump\fR uses fuzzy matching to find the desired directory to jump to\. This means that your search terms are patterns that match the desired directory approximately rather than exactly\. Typing \fB2\fR to \fB5\fR consecutive characters of the base directory names is all that \fBjump\fR needs to find it\.
.
.SS "REGULAR JUMP"
The default search behavior of \fBjump\fR is to case insensitively match only the base directory path of the scored directories\. This is because absolute paths are long and short search terms can fuzzy match them easily, lead to bad matches\.
.
.P
If you visit the directory \fB/Users/genadi/Development/rails/web\-console\fR often, you can jump to it by:
.
.IP "" 4
.
.nf

$ j wc      # or\.\.\.
$ j webc    # or\.\.\.
$ j console # or\.\.\.
$ j b\-c     # or\.\.\.
.
.fi
.
.IP "" 0
.
.P
Of course, \fBweb\-console\fR can be typed directly as a search term:
.
.IP "" 4
.
.nf

$ j web\-console
$ pwd
/Users/genadi/Development/rails/web\-console
.
.fi
.
.IP "" 0
.
.P
Using jump is all about saving key strokes\. However, if you made the effort to type a directory base name exactly, \fBjump\fR will try to find the exact match, rather than fuzzy search\.
.
.SS "DEEP JUMP"
Given the following directories:
.
.IP "" 4
.
.nf

/Users/genadi/Development/society/website
/Users/genadi/Development/chaos/website
.
.fi
.
.IP "" 0
.
.P
Can you be sure where \fBj web\fR will lead you? You can hint jump where you want to go\. To ensure a match of \fB/Users/genadi/Development/chaos/website\fR, use the search term:
.
.IP "" 4
.
.nf

$ j ch web
$ pwd
/Users/genadi/Development/chaos/website
.
.fi
.
.IP "" 0
.
.P
This instructs \fBjump\fR to look for a \fBweb\fR match inside that is preceded by a \fBch\fR match in the parent directory\. The search is normalized only on the last two parts of the target paths\. This will ensure a better match, because of the shorter path to fuzzy match on\.
.
.P
There are no depth limitations though and a jump to \fB/Users/genadi/Development/society/website\fR can look like:
.
.IP "" 4
.
.nf

$ j dev soc web
$ pwd
/Users/genadi/Development/society/website
.
.fi
.
.IP "" 0
.
.P
In fact, every space passed to \fBj\fR is converted to an OS separator\. The search term above can be expressed as:
.
.IP "" 4
.
.nf

$ j dev/soc/web
$ pwd
/Users/genadi/Development/society/website
.
.fi
.
.IP "" 0
.
.SH "REVERSE JUMP"
Sometimes bad jumps happen\. Maybe the search has a better scored directory already\. If we want to jump to \fB/Users/genadi/Development/hack/website\fR and we have the following entries in the database:
.
.IP "" 4
.
.nf

/Users/genadi/Development/society/website
/Users/genadi/Development/chaos/website
/Users/genadi/Development/hack/website
.
.fi
.
.IP "" 0
.
.P
Typing \fBj web\fR would lead to:
.
.IP "" 4
.
.nf

$ j web
$ pwd
/Users/genadi/Development/society/website
.
.fi
.
.IP "" 0
.
.P
Instead of typing another search term, typing \fBj\fR without a search term will instruct \fBjump\fR to the second best, third best and so on matches\.
.
.IP "" 4
.
.nf

$ j
$ pwd
/Users/genadi/Development/chaos/website

$ j
$ pwd
/Users/genadi/Development/hack/website
.
.fi
.
.IP "" 0
.
.SS "CASE SENSITIVE JUMP"
To trigger a case\-sensitive search, use a term that has a capital letter\.
.
.IP "" 4
.
.nf

$ j Dev
$ pwd
/Users/genadi/Development
.
.fi
.
.IP "" 0
.
.P
The jump will resolve to \fB/Users/genadi/Development\fR even if there is \fB/Users/genadi/Development/dev\-tools\fR that scores better\.
.
.SH "COPYRIGHT"
The MIT License (MIT)
.
.P
Copyright (c) 2015\-2018 Genadi Samokovarov
.
.SH "SEE ALSO"
autojump(1), z(1), pushd(1), popd(1)
