package shell

// Bash is the bash shell integration.
var Bash = Shell(`# Put the line below in ~/.bashrc or ~/bash_profile:
#
#   eval "$(jump shell bash)"	
#
# The following lines are autogenerated:

__jump_prompt_command() {
  local status=$?
  jump chdir && return $status
}

[[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
  PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"
}

{{.Bind}}() {
  local dir="$(jump cd $@)"
  test -d "$dir"  && cd "$dir"
}

complete -o dirnames -C 'jump hint "${COMP_LINE/#{{.Bind}} /}" --smart' {{.Bind}}
`)
