package shell

// Fish is the fish shell integration.
var Fish = Shell(`# Put the line below in ~/.config/fish/config.fish:
#
#   jump shell fish | source
#
# The following lines are autogenerated:

function __jump_add --on-variable PWD
  status --is-command-substitution; and return
  jump chdir
end

function __jump_hint
  set -l term (string replace -r '^{{.Bind}} ' '' -- (commandline -cp))
  jump hint "$term"
end

function {{.Bind}}
  set -l dir (jump cd $argv)
  test -d "$dir"; and cd "$dir"
end

{{if .BasedBind}}
function {{.BasedBind}}
  set -l base_dir $JUMP_BASE_DIR
  if test -z "$base_dir"
    set base_dir "$(command git rev-parse --show-toplevel 2>/dev/null)"
  end
	{{.Bind}} "$base_dir" $argv
end
{{end}}

complete --command {{.Bind}} --exclusive --arguments '(__jump_hint)'
`)
