# Put the line below in ~/.config/fish/config.fish:
#
#   jump shell fish | source
#
# The following lines are autogenerated:

function __jump_add --on-variable PWD
    status --is-command-substitution; and return
    jump chdir
end

function __jump_hint
    set -l term (commandline --cut-at-cursor --current-token)
    set -l local_dirs (complete --do-complete "cd $term" | string match --regex -- '.*/$')

    if test (count $local_dirs) -gt 0
        printf '%s\n' $local_dirs
    else if not string match -q '*/*' -- $term
        jump hint "$term" | head -1
    end
end

function __jump_base_dir
    set -l base_dir $JUMP_BASED_PATH
    if test -n "$base_dir"
        echo "$base_dir"
    else if set -l git_dir (command git rev-parse --show-toplevel 2>/dev/null)
        echo "$git_dir"
    else
        pwd
    end
end

function __jump_cd
    set -l previous $PWD
    builtin cd $argv; or return
    test "$PWD" = "$previous"; and return

    status --is-command-substitution; and return
    set -g dirprev $dirprev[-24..-1] $previous
    set -q dirnext; and set -e dirnext
    set -g __fish_cd_direction prev
    true
end

function {{.Bind}}
    switch "$argv[1]"
        case ".."
            __jump_cd ..
        case -
            set -q dirprev[1]; or set -q dirnext[1]; or return
            if test "$__fish_cd_direction" = next
                nextd
            else
                prevd
            end
        case "."
            set argv[1] (__jump_base_dir)
            set -l dir (jump cd $argv)
            test -d "$dir"; and __jump_cd "$dir"
        case '*'
            set -l dir (jump cd $argv)
            test -d "$dir"; and __jump_cd "$dir"
    end
end

complete --command {{.Bind}} --erase
complete --command {{.Bind}} --no-files --arguments '(__jump_hint)'
