# Put the line below in ~/.zshrc:
#
#   eval "$(jump shell zsh)"
#
# The following lines are autogenerated:

__jump_chpwd() {
  jump chdir
}

jump_completion() {
  reply="'$(jump hint "$@")'"
}

__jump_base_dir() {
  local base_dir="$JUMP_BASED_PATH"
  if [ -z "$base_dir" ]; then
    base_dir="$(command git rev-parse --show-toplevel 2>/dev/null)"
  fi
  echo "$base_dir"
}

{{.Bind}}() {
  local dir
  if [ "$1" = "." ]; then
    shift
    dir="$(jump cd "$(__jump_base_dir)" $@)"
  else
    dir="$(jump cd $@)"
  fi

  test -d "$dir" && cd "$dir"
}

typeset -gaU chpwd_functions
chpwd_functions+=__jump_chpwd

compctl -U -K jump_completion {{.Bind}}
