# Put the line below in ~/.bashrc or ~/bash_profile:
#
#   eval "$(jump shell bash)"
#
# The following lines are autogenerated:

__jump_prompt_command() {
  local status=$?
  jump chdir && return $status
}

__jump_hint() {
  [[ ${#COMP_WORDS[@]} -eq $((COMP_CWORD + 1)) ]] || return

  if [[ ${#COMP_WORDS[@]} -eq 2 ]]; then
    mapfile -t COMPREPLY < <(compgen -A directory -- "${COMP_WORDS[COMP_CWORD]}")
  else
    mapfile -t COMPREPLY < <(jump hint "${COMP_WORDS[@]:1}")
  fi
}

__jump_base_dir() {
  local base_dir="$JUMP_BASED_PATH"
  if [ -z "$base_dir" ]; then
    base_dir="$(command git rev-parse --show-toplevel 2>/dev/null)"
  fi
  echo "$base_dir"
}

{{.Bind}}() {
  local dir
  if [ "$1" = "." ]; then
    shift
    dir="$(jump cd "$(__jump_base_dir)" $@)"
  else
    dir="$(jump cd $@)"
  fi
  test -d "$dir"  && cd "$dir"
}

[[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
  PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"
}

complete -F __jump_hint -o filenames -- {{.Bind}}
