package shell

// Nushell is the nushell shell integration.
var Nushell = Shell(`# Put the line below in your Nushell config file:
#
#   jump shell nushell | save --append $nu.config-path
#
# The following lines are autogenerated:

$env.config = ($env.config | upsert hooks {
  pre_prompt: ($env.config.hooks.pre_prompt? | default [] | append {||
    jump chdir
  })
})

def jump-completer [context: string, position: int] {
  let cmd_line = $context | str substring 0..$position
  let terms = $cmd_line | split row ' ' | skip 1 | str join ' ' | str trim
  let completions = jump hint $terms | lines
  {
    options: { case_sensitive: false, completion_algorithm: "fuzzy", sort: false },
    completions: $completions
  }
}

def --env {{.Bind}} [...terms: string@jump-completer] {
  let dir = (jump cd ...$terms | str trim)
  if ($dir | path exists) {
    cd $dir
  }
}
`)
