package shell

// Pwsh is the PowerShell shell integration.
var Pwsh = Shell(`# Put the line below in your PowerShell profile (Microsoft.PowerShell_profile.ps1):
#
#   Invoke-Expression (&jump shell pwsh | Out-String)
#
# You can locate your profile by typing $PROFILE in PowerShell.
#
# The following lines are autogenerated:

function Set-Location
{
    [CmdletBinding()]
    param(
        [Parameter(Position=0)]
        [System.Object]
        ${Path})

    $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand('Microsoft.PowerShell.Management\Set-Location', [System.Management.Automation.CommandTypes]::Function)
    & $wrappedCmd @PSBoundParameters
    jump chdir
}

function Push-Location
{
    [CmdletBinding()]
    param(
        [Parameter(Position=0)]
        [System.Object]
        ${Path})

    $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand('Microsoft.PowerShell.Management\Push-Location', [System.Management.Automation.CommandTypes]::Function)
    & $wrappedCmd @PSBoundParameters
    jump chdir
}

if (Get-Command Register-ArgumentCompleter -ErrorAction Ignore) {
    Register-ArgumentCompleter -CommandName '{{.Bind}}' -ScriptBlock {
        param ($commandName, $wordToComplete, $commandAst, $fakeBoundParameter)
        jump hint $wordToComplete | ForEach-Object {
            if ($_ -match '\s') { "'$_'" } else { $_ }
        }
    }
}

function {{.Bind}}
{
    $Path = jump cd $Args
    if (Test-Path $Path) {
        Set-Location $Path
    }
}

{{if .BasedBind}}
function {{.BasedBind}}
{
    $BasePath = if ($env:JUMP_BASED_PATH) { $env:JUMP_BASED_PATH } else { git rev-parse --show-toplevel 2>$null }
    {{.Bind}} $BasePath @Args
}
{{end}}
`)
