package shell

var Zsh = Shell(`# Put the line below in ~/.zshrc:
#
#   eval "$(jump shell)"	
#
# The following lines are autogenerated:

__jump_chpwd() {
  jump update
}

typeset -gaU chpwd_functions
chpwd_functions+=__jump_chpwd

j() {
  local dir="$(jump cd $@)"
  test -d "$dir" && cd "$dir"
}
`)
