package shell

// Zsh is the zsh shell integration.
var Zsh = Shell(`# Put the line below in ~/.zshrc:
#
#   eval "$(jump shell zsh)"
#
# The following lines are autogenerated:

__jump_chpwd() {
  jump chdir
}

jump_completion() {
  reply="'$(jump hint "$@")'"
}

{{.Bind}}() {
  local dir="$(jump cd $@)"
  test -d "$dir" && cd "$dir"
}

{{if .BasedBind}}
{{.BasedBind}}() {
  local base_path="${JUMP_BASED_PATH:-$(command git rev-parse --show-toplevel 2>/dev/null)}"
  {{.Bind}} "$base_path" $@
}
{{end}}

typeset -gaU chpwd_functions
chpwd_functions+=__jump_chpwd

compctl -U -K jump_completion {{.Bind}}
`)
